name: reefwatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - scikit-image
  - rasterio
  - rioxarray
  - xarray
  - h5netcdf
  - earthaccess
  - pillow
  - requests
  - dask
  - toolz
  - pyyaml
  - cloudpickle
  - partd
  - pip:
    - python-cmr
    - pyproj
    - pqdm
    - networkx
    - multimethod
    - lazy-loader
    - importlib-resources
    - imageio
    - tifffile
    - tinynetrc
    - s3fs
    - botocore
    - aiohttp
    - aiobotocore
    - aiohappyeyeballs
    - aiosignal
    - async-timeout
    - attrs
    - bounded-pool-executor
    - charset_normalizer
    - click
    - click-plugins
    - cligj
    - frozenlist
    - idna
    - importlib-metadata
    - importlib-resources
    - jmespath
    - propcache
    - pytz
    - tenacity
    - typing-extensions
    - urllib3
    - wrapt
    - yarl
    - zipp